version: '3'
services:
  web:
    container_name: service
    image: sunwupark/meme-service
    expose:
      - 8080
    ports:
      - "8080:8080"

  auth:
    container_name: auth
    image: sunwupark/meme-auth
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on: web
