version: '3'
services:
  web:
    container_name: service
    image: sunwupark/meme-service
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASS=${DB_PASS}
